import { Metadata } from 'next'
import { MainLayout } from '@poslive/core/layouts'

export default MainLayout

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: 'Poslive',
    description: 'Generated by Poslive.id',
  }
}
